// Code generated by MockGen. DO NOT EDIT.
// Source: application/types.go
//
// Generated by this command:
//
//	mockgen -source=application/types.go -destination=./application/mock/types_mock.go -package=application
//

// Package application is a generated GoMock package.
package application
