name: 'Execute Scripts GitHub Flow'
description: 'Execute scripts in target file list when the labeled pull request is merged'
inputs:
  requiredLabel:
    description: 'Required labels to execute script on merge'
    required: true
  baseBranch:
    description: 'Execute script if the base branch of the pull request matches with this value'
    default: 'main'
    required: false
  targetScriptListDir:
    description: 'Directory that contains target script list'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: See Directory
      run: ls
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: See Directory
      run: ls
      shell: bash

    - name: Execute
      run: make run
      shell: bash
      env:
        INPUT_REQUIREDLABEL: ${{ inputs.requiredLabel }}
        INPUT_BASEBRANCH: ${{ inputs.baseBranch }}
        INPUT_TARGETSCRIPTLISTDIR: ${{ inputs.targetScriptListDir }}
