// Code generated by MockGen. DO NOT EDIT.
// Source: domain/types.go
//
// Generated by this command:
//
//	mockgen -source=domain/types.go -destination=./domain/mock/types_mock.go -package=domain
//

// Package domain is a generated GoMock package.
package domain

import (
	reflect "reflect"

	domain "github.com/Rindrics/execute-script-with-merge/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventParser is a mock of EventParser interface.
type MockEventParser struct {
	ctrl     *gomock.Controller
	recorder *MockEventParserMockRecorder
}

// MockEventParserMockRecorder is the mock recorder for MockEventParser.
type MockEventParserMockRecorder struct {
	mock *MockEventParser
}

// NewMockEventParser creates a new mock instance.
func NewMockEventParser(ctrl *gomock.Controller) *MockEventParser {
	mock := &MockEventParser{ctrl: ctrl}
	mock.recorder = &MockEventParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventParser) EXPECT() *MockEventParserMockRecorder {
	return m.recorder
}

// ParseEvent mocks base method.
func (m *MockEventParser) ParseEvent() (domain.ParsedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseEvent")
	ret0, _ := ret[0].(domain.ParsedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseEvent indicates an expected call of ParseEvent.
func (mr *MockEventParserMockRecorder) ParseEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseEvent", reflect.TypeOf((*MockEventParser)(nil).ParseEvent))
}

// ParseTargetScripts mocks base method.
func (m *MockEventParser) ParseTargetScripts(arg0 domain.ParsedEvent, arg1 string) ([]domain.TargetScript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTargetScripts", arg0, arg1)
	ret0, _ := ret[0].([]domain.TargetScript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTargetScripts indicates an expected call of ParseTargetScripts.
func (mr *MockEventParserMockRecorder) ParseTargetScripts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTargetScripts", reflect.TypeOf((*MockEventParser)(nil).ParseTargetScripts), arg0, arg1)
}

// MockTargetScriptListValidator is a mock of TargetScriptListValidator interface.
type MockTargetScriptListValidator struct {
	ctrl     *gomock.Controller
	recorder *MockTargetScriptListValidatorMockRecorder
}

// MockTargetScriptListValidatorMockRecorder is the mock recorder for MockTargetScriptListValidator.
type MockTargetScriptListValidatorMockRecorder struct {
	mock *MockTargetScriptListValidator
}

// NewMockTargetScriptListValidator creates a new mock instance.
func NewMockTargetScriptListValidator(ctrl *gomock.Controller) *MockTargetScriptListValidator {
	mock := &MockTargetScriptListValidator{ctrl: ctrl}
	mock.recorder = &MockTargetScriptListValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetScriptListValidator) EXPECT() *MockTargetScriptListValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockTargetScriptListValidator) Validate(list domain.TargetScriptList) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", list)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockTargetScriptListValidatorMockRecorder) Validate(list any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockTargetScriptListValidator)(nil).Validate), list)
}
